name: Build android

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: 'adopt'

      - name: Expo Prebuild 
        run: yarn expo prebuild --platform android

      - name: make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Build android APK
        run: cd ./android && ./gradlew :app:assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
